name: Linux cp Command Autograding

on:
  push:
  pull_request:

jobs:

  grade:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout student submission
        uses: actions/checkout@v4

      - name: Give execute permission
        run: |
          chmod +x starter/solution.sh
          chmod +x tests/test_cp.sh

      - name: Run Autograder
        run: |
          bash tests/test_cp.sh
